# Hugo Theme Configuration for Parsa Redesigned
# This is the theme-level configuration file

# Basic Hugo settings
baseURL = "https://example.com"
languageCode = "en-us"
title = "Parsa Hugo Demo"
# theme = "parsa-hugo"  # 註解掉，因為這是主題本身

# Hugo version requirements
[module]
  [module.hugoVersion]
    extended = true
    min = "0.147.2"
    max = ""

# Hugo Modules configuration
[[module.imports]]
  path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
  disable = true  # We use Tailwind CSS instead

# Mount points for theme assets
[[module.mounts]]
  source = "assets"
  target = "assets"

[[module.mounts]]
  source = "layouts"
  target = "layouts"

[[module.mounts]]
  source = "static"
  target = "static"

[[module.mounts]]
  source = "i18n"
  target = "i18n"

# Content and taxonomy configuration
[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

# Output formats for search and feeds
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

# Markup configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      linkify = true
      strikethrough = true
      table = true
      taskList = true
  [markup.highlight]
    style = "github"
    lineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 4

# Sitemap configuration
[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

# Privacy configuration
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = true
    anonymizeIP = true
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

# Theme parameters
[params]
  # Design and branding
  logo = "/images/logo.svg"
  favicon = "/favicon.ico"
  
  # Color scheme
  [params.colors]
    primary = "#3b82f6"
    accent = "#8b5cf6"
    background = "#ffffff"
    foreground = "#0f172a"
    muted = "#64748b"
    border = "#e2e8f0"
    card = "#ffffff"
    
  # Typography
  [params.typography]
    fontFamily = "Inter, system-ui, sans-serif"
    headingFamily = "Inter, system-ui, sans-serif"
    monoFamily = "JetBrains Mono, Consolas, monospace"
    
  # Layout settings
  [params.layout]
    articlesPerPage = 9
    featuredArticlesCount = 2
    relatedArticlesCount = 3
    excerptLength = 160
    readMoreText = "Read More"
    
  # Feature toggles
  [params.features]
    search = true
    tagCloud = true
    animations = true
    darkMode = false
    socialSharing = true
    relatedArticles = true
    breadcrumbs = true
    tableOfContents = true
    readingTime = true
    wordCount = true
    lastModified = true
    
  # SEO and social media
  [params.seo]
    enableOpenGraph = true
    enableTwitterCard = true
    enableJsonLd = true
    enableSitemap = true
    enableRobots = true
    
  # OpenGraph default settings
  [params.openGraph]
    siteName = "Parsa Redesigned"
    defaultImage = "/images/og-default.jpg"
    twitterSite = "@username"
    facebookAppId = ""
    locale = "en_US"
    
  # Social media links
  [params.social]
    twitter = "https://twitter.com/username"
    facebook = "https://facebook.com/username"
    instagram = "https://instagram.com/username"
    linkedin = "https://linkedin.com/in/username"
    github = "https://github.com/username"
    youtube = "https://youtube.com/c/username"
    email = "contact@example.com"
    
  # Author information
  [params.author]
    name = "Default Author"
    image = "/images/author.jpg"
    bio = "A passionate writer and content creator sharing insights on technology, design, and digital innovation."
    email = "author@example.com"
    
  # Comments system (Disqus)
  [params.comments]
    enable = true
    disqusShortname = "your-disqus-shortname"
    
  # Analytics and Tracking
  [params.analytics]
    googleAnalytics = "G-XXXXXXXXXX"
    googleTagManager = ""
    
  # Google AdSense Configuration
  [params.adsense]
    enabled = false
    client = ""  # Format: ca-pub-XXXXXXXXXXXXXXXX
    inArticleSlot = ""  # Format: 10 digits
    autoAds = false
    responsive = true
    lazyLoad = true
    
    # Ad placement configuration
    [params.adsense.placements]
      header = false
      sidebar = false
      footer = false
      inContent = false
      beforeContent = false
      afterContent = false
      
  # Facebook Pixel Configuration
  [params.facebookPixel]
    enabled = false
    pixelId = ""  # Format: 15-16 digits
    advancedMatching = false
    
    # Event tracking configuration
    [params.facebookPixel.events]
      pageView = true
      viewContent = false
      search = false
      contact = false
      lead = false
      completeRegistration = false
      
  # Google Custom Search Engine Configuration
  [params.gcs_engine_id]
    value = ""  # Format: 17 character hexadecimal string
    
  [params.googleCustomSearch]
    engineId = ""  # Alternative configuration path
    enabled = false
    autoComplete = true
    enableHistory = true
    maxCompletions = 5
    fallbackToLocal = true
    
  # Mermaid Diagrams Configuration
  [params.mermaid]
    enabled = true
    theme = "default"  # Options: default, dark, forest, neutral, base
    startOnLoad = true
    securityLevel = "loose"
    
    [params.mermaid.flowchart]
      useMaxWidth = true
      htmlLabels = true
    
  # Search configuration
  [params.search]
    enable = true
    placeholder = "Search articles..."
    maxResults = 10
    minQueryLength = 2
    
  # Performance Optimization Settings
  [params.performance]
    # Legacy settings (maintained for compatibility)
    lazyLoading = true
    webpImages = true
    minifyCSS = true
    minifyJS = true
    
    # New analytics and advertising performance settings
    lazyLoadAds = true
    asyncScripts = true
    resourceHints = true
    criticalCSS = false
    
    # Preconnect domains for external services
    preconnectDomains = [
      "https://www.googletagmanager.com",
      "https://pagead2.googlesyndication.com",
      "https://connect.facebook.net",
      "https://cse.google.com",
      "https://cdn.jsdelivr.net"
    ]
    
  # Security Configuration
  [params.security]
    contentSecurityPolicy = false
    subresourceIntegrity = false
    httpsOnly = true
    noSniff = true
    
  # Multilingual settings
  [params.i18n]
    defaultLanguage = "en"
    dateFormat = "January 2, 2006"
    timeFormat = "15:04"
    
  # Custom CSS and JS
  [params.custom]
    css = []
    js = []
    
  # Newsletter subscription
  [params.newsletter]
    enable = false
    provider = "mailchimp"
    action = "https://your-mailchimp-url"
    title = "Subscribe to our newsletter"
    subtitle = "Get the latest articles delivered to your inbox"
    
  # Privacy and Consent Management
  [params.privacy]
    respectDoNotTrack = true
    cookieConsent = false
    anonymizeIP = true
    disableTracking = false
    
    # Cookie consent banner configuration
    [params.privacy.consentBanner]
      enabled = false
      message = "This website uses cookies to ensure you get the best experience."
      acceptText = "Accept"
      declineText = "Decline"
      learnMoreText = "Learn More"
      learnMoreUrl = "/privacy-policy"
      
  # Legacy cookie consent (deprecated - use params.privacy.consentBanner)
  [params.cookies]
    enable = false
    message = "This website uses cookies to ensure you get the best experience."
    dismiss = "Got it!"
    link = "/privacy-policy/"
    
# Menu configuration
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
    
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
    
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
    
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5
    
  # Footer menu
  [[menu.footer]]
    name = "Privacy Policy"
    url = "/privacy-policy/"
    weight = 1
    
  [[menu.footer]]
    name = "Terms of Service"
    url = "/terms/"
    weight = 2
    
  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
    weight = 3

# Language configuration for multilingual support
[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-US"
    weight = 1
    title = "Parsa Redesigned"
    
    [languages.en.params]
      description = "A modern, redesigned Hugo theme with Tailwind CSS and contemporary design elements"
      
  [languages.zh]
    languageName = "中文"
    languageCode = "zh-CN"
    weight = 2
    title = "Parsa 重新設計"
    
    [languages.zh.params]
      description = "採用 Tailwind CSS 和現代設計元素的重新設計 Hugo 主題"

# Related content configuration
[related]
  includeNewer = true
  threshold = 80
  toLower = false
  
  [[related.indices]]
    name = "keywords"
    weight = 100
    
  [[related.indices]]
    name = "tags"
    weight = 80
    
  [[related.indices]]
    name = "categories"
    weight = 60
    
  [[related.indices]]
    name = "date"
    weight = 10

# Image processing configuration
[imaging]
  resampleFilter = "CatmullRom"
  quality = 85
  anchor = "smart"
  
  [imaging.exif]
    includeFields = ""
    excludeFields = "GPS|Exif|IPTC|IFD0|IFD1"
    disableDate = false
    disableLatLong = true

# Security configuration
[security]
  enableInlineShortcodes = false
  
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
    
  [security.funcs]
    getenv = ['^HUGO_', '^CI$']
    
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
# Build configuration for performance
[build]
  writeStats = true
  
[caches]
  [caches.getjson]
    maxAge = "10m"
  [caches.getcsv]
    maxAge = "10m"
  [caches.images]
    maxAge = "1h"
  [caches.assets]
    maxAge = "1h"
  [caches.modules]
    maxAge = "1h"

# Minification settings
[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  
  [minify.tdewolff]
    [minify.tdewolff.css]
      keepCSS2 = true
      precision = 0
    [minify.tdewolff.html]
      keepComments = false
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = false
      keepWhitespace = false
    [minify.tdewolff.js]
      keepVarNames = false
      precision = 0
    [minify.tdewolff.json]
      precision = 0
    [minify.tdewolff.svg]
      precision = 0
    [minify.tdewolff.xml]
      keepWhitespace = false
