# Theme metadata following Hugo theme standards
name = "Parsa Redesigned"
license = "MIT"
licenselink = "https://github.com/username/parsa-redesigned/blob/main/LICENSE"
description = "A modern, redesigned version of the Parsa Hugo theme with Tailwind CSS and contemporary design elements"
homepage = "https://github.com/username/parsa-redesigned"
demosite = "https://parsa-redesigned-demo.netlify.app"

# Theme tags for discoverability
tags = [
  "blog", "personal", "modern", "tailwind", "responsive", 
  "multilingual", "seo", "fast", "minimal", "cards", "gradient",
  "performance", "accessibility", "social-sharing"
]

# Theme features
features = [
  "responsive", "tailwind-css", "multilingual", 
  "seo-optimized", "social-sharing", "search", "performance",
  "accessibility", "dark-mode-ready", "hugo-modules"
]

# Hugo version requirements
min_version = "0.147.2"

# Author information
[author]
  name = "Parsa Redesigned Team"
  homepage = "https://github.com/username"
  email = "contact@parsa-redesigned.com"

# Original theme attribution
[original]
  name = "Parsa Hugo"
  homepage = "https://gethugothemes.com/products/parsa-hugo-theme/"
  repo = "https://github.com/themefisher/parsa-hugo"
  author = "Themefisher"