# Example Site Configuration for Parsa Redesigned Theme
# This demonstrates how to configure the theme

baseURL = "https://parsa-redesigned-demo.netlify.app"
languageCode = "en-us"
title = "Parsa Redesigned - Demo Site"
theme = "parsa-redesigned"

# Enable Hugo extended features
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

# Content settings
paginate = 9
paginatePath = "page"
summaryLength = 30
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Hugo Modules
[module]
  [module.hugoVersion]
    extended = true
    min = "0.147.2"

# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

# Output formats (including SEO enhancements)
[outputs]
  home = ["HTML", "RSS", "JSON", "WebAppManifest"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

# Media types for additional outputs
[mediaTypes]
  [mediaTypes."application/manifest+json"]
    suffixes = ["webmanifest"]

[outputFormats]
  [outputFormats.WebAppManifest]
    mediaType = "application/manifest+json"
    rel = "manifest"

# Sitemap configuration
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# Markup settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true

# Google Analytics (replace with your own ID)
GoogleAnalyticsID = "G-JKSVCT23D1"

# Theme parameters - Example configuration
[params]
  # Site information
  description = "A modern, redesigned Hugo theme showcasing contemporary web design with Tailwind CSS"
  author = "Parsa Redesigned Team"
  logo = "/images/logo.png"
  favicon = "/favicon.ico"
  
  # Design settings
  [params.colors]
    primary = "#3b82f6"
    accent = "#8b5cf6"
    
  # Layout settings
  [params.layout]
    articlesPerPage = 9
    featuredArticlesCount = 2
    
  # Features
  [params.features]
    search = true
    tagCloud = true
    animations = true
    socialSharing = true
    relatedArticles = true
    readingTime = true
    
  # SEO Configuration
  keywords = ["hugo", "theme", "blog", "modern", "tailwind", "responsive"]
  
  [params.seo]
    enableSEO = true
    enableOpenGraph = true
    enableTwitterCard = true
    enableStructuredData = true
    defaultImage = "/images/og-default.jpg"
    
    # Site verification codes (add your own)
    googleSiteVerification = ""
    bingSiteVerification = ""
    
    # Social media profiles for structured data
    sameAs = [
      "https://twitter.com/example",
      "https://github.com/example",
      "https://linkedin.com/company/example"
    ]
    
    # Performance optimization
    preconnect = [
      "https://fonts.googleapis.com",
      "https://fonts.gstatic.com"
    ]
    
  [params.openGraph]
    siteName = "Parsa Redesigned Demo"
    twitterSite = "@parsa_redesigned"
    
  # Organization information for structured data
  [params.organization]
    name = "Parsa Redesigned Demo"
    logo = "/images/logo.png"
    
  # PWA settings
  [params.pwa]
    name = "Parsa Redesigned Demo"
    shortName = "Parsa Demo"
    description = "A modern Hugo theme demonstration"
    themeColor = "#3b82f6"
    backgroundColor = "#ffffff"
    
  # Author info
  [params.author]
    name = "Demo Author"
    image = "/images/author.jpg"
    bio = "Demonstrating the capabilities of the Parsa Redesigned theme with modern design and functionality."
    
  # Social links
  [params.social]
    twitter = "https://twitter.com/example"
    github = "https://github.com/example"
    linkedin = "https://linkedin.com/in/example"
    
  # Search
  [params.search]
    placeholder = "Search articles..."
    
  # Analytics and Advertising Configuration Examples
  # Note: These are example configurations - replace with your own IDs
  
  # Google AdSense (disabled by default)
  [params.adsense]
    enabled = false  # Set to true and add your client ID to enable
    client = "ca-pub-2970874383549118"  # Replace with your AdSense client ID
    inArticleSlot = "4383549118"  # Replace with your in-article ad slot ID
    autoAds = false
    
    [params.adsense.placements]
      sidebar = true
      footer = true
      inContent = false
      
  # Facebook Pixel (disabled by default)
  [params.facebookPixel]
    enabled = false  # Set to true and add your pixel ID to enable
    pixelId = "123456789012345"  # Replace with your Facebook Pixel ID
    
    [params.facebookPixel.events]
      pageView = true
      search = true
      contact = true
      
  # Google Custom Search Engine (optional)
  [params.gcs_engine_id]
    value = ""  # Add your Google Custom Search Engine ID here
    
  # Mermaid Diagrams (enabled by default)
  [params.mermaid]
    enabled = true
    theme = "default"
    
  # Privacy and Consent Management
  [params.privacy]
    respectDoNotTrack = true
    cookieConsent = false  # Enable for GDPR compliance
    anonymizeIP = true
    
    [params.privacy.consentBanner]
      enabled = false
      message = "This website uses cookies to enhance your experience."
      acceptText = "Accept"
      declineText = "Decline"
      learnMoreUrl = "/privacy-policy"
      
  # Performance Optimization
  [params.performance]
    lazyLoadAds = true
    asyncScripts = true
    resourceHints = true
    
  # Security Settings
  [params.security]
    httpsOnly = true
    noSniff = true
    
# Navigation menus
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
    
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
    
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
    
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

# Languages
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    
  [languages.zh]
    languageName = "中文"
    weight = 2