# Example Site Configuration for Parsa Hugo Theme
# Complete integration demonstration

baseURL = "https://parsa-hugo-demo.netlify.app"
languageCode = "en-us"
title = "Parsa Hugo - Complete Integration Demo"
theme = "parsa-hugo"

# Enable Hugo extended features
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

# Content settings
[pagination]
  pagerSize = 9
  path = "page"

summaryLength = 30
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"
  authors = "authors"

# Output formats (including SEO enhancements)
[outputs]
  home = ["HTML", "RSS", "JSON", "WebAppManifest"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

# Media types for additional outputs
[mediaTypes]
  [mediaTypes."application/manifest+json"]
    suffixes = ["webmanifest"]

[outputFormats]
  [outputFormats.WebAppManifest]
    mediaType = "application/manifest+json"
    rel = "manifest"

# Sitemap configuration
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# Markup settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true

# Google Analytics (enabled for demonstration)
GoogleAnalyticsID = "G-JKSVCT23D1"

# Theme parameters - Complete integration configuration
[params]
  # Site information
  description = "Complete integration demonstration of Hugo theme with analytics, advertising, search, and diagram features"
  logo = "/images/logo.png"
  favicon = "/favicon.ico"
  
  # Design settings
  [params.colors]
    primary = "#3b82f6"
    accent = "#8b5cf6"
    
  # Layout settings
  [params.layout]
    articlesPerPage = 9
    featuredArticlesCount = 2
    
  # Features
  [params.features]
    search = true
    tagCloud = true
    animations = true
    socialSharing = true
    relatedArticles = true
    readingTime = true
    
  # SEO Configuration
  keywords = ["hugo", "theme", "blog", "analytics", "advertising", "integration"]
  
  [params.seo]
    enableSEO = true
    enableOpenGraph = true
    enableTwitterCard = true
    enableStructuredData = true
    defaultImage = "/images/og-default.jpg"
    
    # Site verification codes
    googleSiteVerification = ""
    bingSiteVerification = ""
    
    # Social media profiles for structured data
    sameAs = [
      "https://twitter.com/example",
      "https://github.com/example",
      "https://linkedin.com/company/example"
    ]
    
    # Performance optimization
    preconnect = [
      "https://fonts.googleapis.com",
      "https://fonts.gstatic.com",
      "https://www.googletagmanager.com",
      "https://connect.facebook.net"
    ]
    
  [params.openGraph]
    siteName = "Parsa Hugo Integration Demo"
    twitterSite = "@parsa_hugo"
    
  # Organization information for structured data
  [params.organization]
    name = "Parsa Hugo Integration Demo"
    logo = "/images/logo.png"
    
  # PWA settings
  [params.pwa]
    name = "Parsa Hugo Integration Demo"
    shortName = "Parsa Demo"
    description = "Complete integration demonstration of modern Hugo theme features"
    themeColor = "#3b82f6"
    backgroundColor = "#ffffff"
    
  # Author info (correct structure based on Hugo docs)
  [params.author]
    name = "Integration Demo Author"
    email = "demo@example.org"
    image = "/images/author.jpg"
    bio = "Demonstrating the complete integration of analytics, advertising, search, and diagram features in Hugo themes."
    
  # Social links
  [params.social]
    twitter = "https://twitter.com/example"
    github = "https://github.com/example"
    linkedin = "https://linkedin.com/in/example"
    
  # Search
  [params.search]
    placeholder = "Search articles..."
    
  # Analytics and Advertising Configuration - FULLY ENABLED
  
  # Google AdSense (enabled for complete integration)
  [params.adsense]
    enabled = true
    client = "ca-pub-2970874383549118"
    inArticleSlot = "4383549118"
    autoAds = true
    
    [params.adsense.placements]
      header = true
      sidebar = true
      footer = true
      inContent = true
      
  # Facebook Pixel (enabled for complete integration)
  [params.facebookPixel]
    enabled = true
    pixelId = "123456789012345"
    
    [params.facebookPixel.events]
      pageView = true
      viewContent = true
      search = true
      contact = true
      
  # Google Custom Search Engine (enabled for complete integration)
  [params.gcs_engine_id]
    value = "3164aa570fbbb474a"
    
  # Mermaid Diagrams (enabled for complete integration)
  [params.mermaid]
    enabled = true
    theme = "default"
    
  # Privacy and Consent Management (enabled for GDPR compliance)
  [params.privacy]
    respectDoNotTrack = true
    cookieConsent = true
    anonymizeIP = true
    
    [params.privacy.consentBanner]
      enabled = true
      message = "This website uses cookies and analytics to enhance your experience and provide personalized content."
      acceptText = "Accept All"
      declineText = "Decline"
      learnMoreUrl = "/privacy-policy"
      
  # Performance Optimization (enabled for complete integration)
  [params.performance]
    lazyLoadAds = true
    asyncScripts = true
    resourceHints = true
    
  # Security Settings
  [params.security]
    httpsOnly = true
    noSniff = true

# Navigation menus
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
    
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
    
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
    
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

  [[menu.main]]
    name = "Privacy Policy"
    url = "/privacy-policy/"
    weight = 6

# Languages (single language for now, but ready for multilingual)
[languages]
  [languages.en]
    languageName = "English"
    weight = 1